apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-monitoring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-monitoring
  template:
    metadata:
      labels:
        app: network-monitoring
    spec:
      containers:
        - name: network-monitoring-app
          image: network-monitoring-app:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: network-monitoring-service
spec:
  selector:
    app: network-monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
